### ISSUE TITLE
Enpoint not working User.create_session

### ISSUE THREAD

**Issue by karlstenlund** [abhitopia/TypeGenieAPIClient#5]
Create session is sending a POST to https://api.typegenie.net/api/v1/agent/session. 
This uses a different prefix 'agent' then  the other endpoints in the user API, 'user' Which is supposed to be the correct one?

https://github.com/abhitopia/TypeGenieAPIClient/blob/5677351071d2599b95a5ae94d3fc38e74cb1be47/src/typegenie/api.py#L221

**Comment by abhitopia** [comment]
@karlstenlund - it looks like a documentation error where we have a typo. The code seems correct to me. Let me know if you face issues calling any of the end points.
